name: Bike Rental ETL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  etl_job:
    runs-on: ubuntu-latest

    env:
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}   # Use the secret you set in GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pandas psycopg2-binary python-dotenv jupyter nbconvert

      - name: Run ETL Notebook
        run: |
          jupyter nbconvert --to notebook --execute Bike_rental.ipynb --output Bike_rental_out.ipynb
