name: Bike Rental ETL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  etl_job:
    runs-on: ubuntu-latest
    environment: PG_PASSWORD   # <- link to your environment containing PG_PASSWORD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pandas psycopg2-binary python-dotenv jupyter nbconvert

      - name: Run ETL Notebook
        env:
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}   # <-- Pass secret into notebook execution
        run: |
          jupyter nbconvert --to notebook --execute Bike_rental.ipynb --output Bike_rental_out.ipynb
